### ISSUE TITLE
API

### ISSUE THREAD

**Issue by jedisct1** [aead/hydrogen#1]
Hi,

And congrats for kicking off this project!

As a side note, for a new project using a libsodium-like API, I would recommend taking a look at the Hydrogen API instead: https://github.com/jedisct1/libhydrogen/wiki

This is essentially how the API from libsodium2 will look like.

**Comment by aead** [comment]
Thanks, first issue from the libsodium founder - great :wink: 

Thanks for the reference, I'll keep an eye on that - There is still some thinking about how this Go API should look like and what features (all, or some) of libsodium should be supported.
For example there is "no" reason to support SipHash because Go provides the built-in map type...

The idea of Hydrogen is great, so maybe I'll focus compatibility with the libhydrogen / libsodium2 library.

**Comment by aead** [comment]
I've taken a look at libhydrogen - I really like the idea of the project, so I'm going to focus to be compatible to your library and provide a go implementation of libhydrogen.
Thanks again for the hint :smile:
